export interface Symptom {
  name: string;
  synonyms: string[];
  riskLevel: "low" | "moderate" | "high";
  description: string;
  relatedConditions: string[];
}

export const symptomDictionary: Symptom[] = [
  // LOW RISK - Common cold/viral symptoms
  {
    name: "runny nose",
    synonyms: ["nasal congestion", "congestion", "sniffles", "rhinitis", "coryza"],
    riskLevel: "low",
    description: "Nasal discharge or stuffiness, typically from viral infections",
    relatedConditions: ["Common Cold", "Allergies", "Seasonal Influenza"],
  },
  {
    name: "sneezing",
    synonyms: ["sneezes", "sternutation"],
    riskLevel: "low",
    description: "Involuntary expulsion of air from nose and mouth",
    relatedConditions: ["Common Cold", "Allergies"],
  },
  {
    name: "sore throat",
    synonyms: ["throat pain", "pharyngitis", "throat irritation", "scratchy throat"],
    riskLevel: "low",
    description: "Pain, scratchiness, or irritation of the throat",
    relatedConditions: ["Common Cold", "Strep Throat", "Pharyngitis"],
  },
  {
    name: "cough",
    synonyms: ["coughing", "hack", "dry cough", "wet cough", "persistent cough"],
    riskLevel: "moderate",
    description: "Reflex action to clear airways of mucus and irritants",
    relatedConditions: ["Common Cold", "Bronchitis", "Asthma", "Pneumonia"],
  },
  {
    name: "mild fever",
    synonyms: ["low fever", "slight fever", "temperature"],
    riskLevel: "low",
    description: "Body temperature elevation (98.6°F - 101°F)",
    relatedConditions: ["Common Cold", "Mild Viral Fever"],
  },
  {
    name: "headache",
    synonyms: ["head pain", "cephalgia", "migraine", "tension headache", "ache"],
    riskLevel: "moderate",
    description: "Pain or pressure in the head region",
    relatedConditions: ["Common Cold", "Migraine", "Tension Headache", "Flu"],
  },
  {
    name: "fatigue",
    synonyms: ["tiredness", "exhaustion", "weakness", "lethargy", "lack of energy"],
    riskLevel: "low",
    description: "Extreme tiredness and lack of energy",
    relatedConditions: ["Common Cold", "Viral Fever", "Anemia"],
  },
  {
    name: "body ache",
    synonyms: ["muscle pain", "myalgia", "muscular pain", "soreness", "aches", "discomfort"],
    riskLevel: "moderate",
    description: "Generalized pain throughout the body",
    relatedConditions: ["Viral Fever", "Influenza", "Fibromyalgia"],
  },
  // MODERATE RISK
  {
    name: "high fever",
    synonyms: ["high temperature", "elevated fever", "persistent fever", "fever above 101"],
    riskLevel: "moderate",
    description: "Sustained body temperature above 101°F (38.3°C)",
    relatedConditions: ["Viral Fever", "Bacterial Infection", "Influenza"],
  },
  {
    name: "nausea",
    synonyms: ["feeling sick", "queasiness", "sickness", "nauseous"],
    riskLevel: "moderate",
    description: "Feeling of sickness and tendency to vomit",
    relatedConditions: ["Gastroenteritis", "Migraine", "Food Poisoning"],
  },
  {
    name: "vomiting",
    synonyms: ["throwing up", "regurgitation", "emesis", "puking"],
    riskLevel: "moderate",
    description: "Expulsion of stomach contents through the mouth",
    relatedConditions: ["Gastroenteritis", "Food Poisoning", "Migraine"],
  },
  {
    name: "diarrhea",
    synonyms: ["loose stool", "loose motion", "dysentery", "gastroenteritis"],
    riskLevel: "moderate",
    description: "Frequent loose or watery bowel movements",
    relatedConditions: ["Gastroenteritis", "Food Poisoning", "IBS"],
  },
  {
    name: "rash",
    synonyms: ["skin irritation", "hives", "dermatitis", "skin lesions", "spots"],
    riskLevel: "moderate",
    description: "Irritation or inflammation of the skin",
    relatedConditions: ["Allergies", "Chicken Pox", "Measles", "Dermatitis"],
  },
  {
    name: "itching",
    synonyms: ["pruritus", "itch", "scratching", "skin itching"],
    riskLevel: "low",
    description: "Sensation causing desire to scratch the skin",
    relatedConditions: ["Allergies", "Eczema", "Dermatitis"],
  },
  // HIGH RISK - CRITICAL SYMPTOMS
  {
    name: "chest pain",
    synonyms: ["chest discomfort", "chest tightness", "cardiac pain", "heart pain"],
    riskLevel: "high",
    description: "Pain or discomfort in the chest area",
    relatedConditions: ["Heart Disease", "Angina", "Heart Attack", "Pneumonia"],
  },
  {
    name: "difficulty breathing",
    synonyms: ["shortness of breath", "dyspnea", "breathlessness", "breathless", "gasping"],
    riskLevel: "high",
    description: "Difficulty or discomfort while breathing",
    relatedConditions: ["Asthma", "Pneumonia", "Heart Disease", "Pulmonary Embolism"],
  },
  {
    name: "severe headache",
    synonyms: ["intense headache", "unbearable headache", "worst headache", "thunderclap headache"],
    riskLevel: "high",
    description: "Severe, incapacitating pain in the head",
    relatedConditions: ["Meningitis", "Migraine", "Stroke", "Aneurysm"],
  },
  {
    name: "vision loss",
    synonyms: ["blurry vision", "loss of sight", "blindness", "vision problems", "cannot see"],
    riskLevel: "high",
    description: "Partial or complete loss of vision",
    relatedConditions: ["Retinal Detachment", "Stroke", "Diabetic Retinopathy"],
  },
  {
    name: "loss of consciousness",
    synonyms: ["unconscious", "fainting", "passed out", "syncope", "collapse"],
    riskLevel: "high",
    description: "Loss of awareness and responsiveness",
    relatedConditions: ["Heart Attack", "Stroke", "Severe Trauma", "Severe Hypotension"],
  },
  {
    name: "severe abdominal pain",
    synonyms: ["acute belly pain", "severe stomach pain", "abdominal cramps", "acute abdomen"],
    riskLevel: "high",
    description: "Intense pain in the abdominal region",
    relatedConditions: ["Appendicitis", "Pancreatitis", "Kidney Stone", "Ectopic Pregnancy"],
  },
  {
    name: "bleeding",
    synonyms: ["hemorrhage", "blood loss", "hemorrhaging", "bleeding heavily"],
    riskLevel: "high",
    description: "Escape of blood from blood vessels",
    relatedConditions: ["Trauma", "Hemorrhagic Fever", "Bleeding Disorders"],
  },
  {
    name: "seizure",
    synonyms: ["convulsion", "fit", "epileptic fit", "convulsing"],
    riskLevel: "high",
    description: "Sudden involuntary contraction of muscles",
    relatedConditions: ["Epilepsy", "Meningitis", "High Fever", "Brain Trauma"],
  },
  // MODERATE - EYE/EAR SYMPTOMS
  {
    name: "eye irritation",
    synonyms: ["eye pain", "eye discomfort", "burning eyes", "eye redness", "red eye"],
    riskLevel: "moderate",
    description: "Discomfort, redness, or burning sensation in the eyes",
    relatedConditions: ["Conjunctivitis", "Eye Strain", "Allergies"],
  },
  {
    name: "ear pain",
    synonyms: ["earache", "otalgia", "ear discomfort"],
    riskLevel: "moderate",
    description: "Pain or discomfort in the ear",
    relatedConditions: ["Otitis Media", "Ear Infection", "Cerumen Impaction"],
  },
  // DEHYDRATION
  {
    name: "dehydration",
    synonyms: ["dry mouth", "excessive thirst", "parched", "dizziness", "dark urine"],
    riskLevel: "moderate",
    description: "Loss of body fluids and electrolytes",
    relatedConditions: ["Diarrhea", "Vomiting", "Heat Exposure", "Excessive Sweating"],
  },
];

export const lowRiskDiseaseDictionary = [
  {
    name: "Common Cold",
    category: "Low Risk - Respiratory",
    symptoms: ["runny nose", "sneezing", "mild fever", "sore throat", "cough", "fatigue"],
    description: "A mild viral infection affecting the upper respiratory tract.",
    dos: ["Drink warm fluids", "Rest well", "Use saline nasal spray", "Stay hydrated"],
    donts: ["Avoid cold exposure", "Avoid self-antibiotics"],
    consult_if: ["Fever > 101°F for 3 days", "Breathing difficulty"],
    typical_duration: "5–7 days",
    remedies: ["Salt water gargle", "Steam inhalation"],
  },
  {
    name: "Mild Dry Cough",
    category: "Low Risk - Respiratory",
    symptoms: ["dry cough", "throat irritation"],
    description: "Non-productive cough often due to mild infection or irritation.",
    dos: ["Warm fluids", "Honey (if age >1 year)", "Steam inhalation"],
    donts: ["Avoid smoking", "Avoid dusty areas"],
    consult_if: ["Cough > 2 weeks", "Chest pain"],
    typical_duration: "3–7 days",
    remedies: ["Ginger tea", "Honey and lemon"],
  },
  {
    name: "Mild Viral Fever",
    category: "Low Risk - General",
    symptoms: ["low-grade fever", "body ache", "fatigue"],
    description: "Short viral illness causing mild fever and weakness.",
    dos: ["Rest", "Hydration"],
    donts: ["Overexertion"],
    consult_if: ["Fever > 102°F", "Lasts > 3 days"],
    typical_duration: "3–5 days",
    remedies: ["Cool compress", "OTC fever reducers (if advised)"],
  },
  {
    name: "Dust Allergy",
    category: "Low Risk - Respiratory",
    symptoms: ["sneezing", "itchy nose", "watery eyes"],
    description: "Allergic reaction triggered by dust exposure.",
    dos: ["Avoid dust", "Use mask", "Keep room clean"],
    donts: ["Avoid allergen exposure"],
    consult_if: ["Breathing difficulty"],
    typical_duration: "Varies",
    remedies: ["Saline nasal rinse", "Anti-allergy medication"],
  },
  {
    name: "Seasonal Allergies",
    category: "Low Risk - Respiratory",
    symptoms: ["sneezing", "itchy eyes", "clear nasal discharge"],
    description: "Allergic response to pollen or seasonal triggers.",
    dos: ["Avoid pollen exposure", "Stay indoors on high pollen days"],
    donts: ["Outdoor exposure during peak pollen"],
    consult_if: ["Breathing problems"],
    typical_duration: "Seasonal",
    remedies: ["Local honey", "Steam inhalation"],
  },
  {
    name: "Migraine",
    category: "Low Risk - Neurological",
    symptoms: ["headache", "nausea", "sensitivity to light"],
    description: "A recurrent throbbing headache that typically affects one side of the head and is often accompanied by nausea and disturbed vision.",
    dos: ["Rest in a dark, quiet room", "Stay hydrated", "Apply cold compress"],
    donts: ["Skip meals", "Consume caffeine or alcohol"],
    consult_if: ["Headache is severe or sudden", "Accompanied by fever or stiff neck"],
    typical_duration: "4–72 hours",
    remedies: ["Peppermint oil", "Cold pack on forehead"],
  },
  {
    name: "Tension Headache",
    category: "Low Risk - Neurological",
    symptoms: ["headache", "neck pain", "muscle tightness"],
    description: "A mild to moderate pain often described as feeling like a tight band around the head.",
    dos: ["Manage stress", "Improve posture", "Take breaks from screen"],
    donts: ["Overuse pain medication", "Skip sleep"],
    consult_if: ["Headaches become frequent", "Interferes with daily life"],
    typical_duration: "30 mins – 7 days",
    remedies: ["Neck massage", "Warm bath"],
  },
  {
    name: "Gastroenteritis (Stomach Flu)",
    category: "Low Risk - Digestive",
    symptoms: ["nausea", "vomiting", "diarrhea", "abdominal cramps", "low-grade fever"],
    description: "Intestinal infection marked by diarrhea, cramps, nausea, vomiting, and fever.",
    dos: ["Drink plenty of fluids", "Eat bland foods (BRAT diet)", "Rest"],
    donts: ["Eat dairy or spicy foods", "Drink caffeine or alcohol"],
    consult_if: ["Signs of dehydration", "Blood in stool", "High fever"],
    typical_duration: "1–3 days",
    remedies: ["Ginger tea", "Peppermint tea", "Oral rehydration salts"],
  },
  {
    name: "Food Poisoning",
    category: "Low Risk - Digestive",
    symptoms: ["nausea", "vomiting", "diarrhea", "abdominal pain", "fever"],
    description: "Illness caused by bacteria or other toxins in food.",
    dos: ["Stay hydrated", "Rest", "Gradually restart eating"],
    donts: ["Take anti-diarrheal medication without advice", "Eat solid foods immediately"],
    consult_if: ["Severe dehydration", "Bloody diarrhea", " fever > 102°F"],
    typical_duration: "12–48 hours",
    remedies: ["Probiotics", "Hydration fluids"],
  },
  {
    name: "Sinusitis",
    category: "Low Risk - Respiratory",
    symptoms: ["facial pain", "nasal congestion", "runny nose", "headache"],
    description: "Inflammation or swelling of the tissue lining the sinuses.",
    dos: ["Steam inhalation", "Warm compress", "Saline nasal spray"],
    donts: ["Smoke", "Expose to dry air"],
    consult_if: ["Symptoms last > 10 days", "High fever", "Vision changes"],
    typical_duration: "2–4 weeks",
    remedies: ["Eucalyptus oil steam", "Warm soup"],
  },
  {
    name: "Acid Reflux (GERD)",
    category: "Low Risk - Digestive",
    symptoms: ["heartburn", "chest pain", "regurgitation", "sore throat"],
    description: "Digestive disease in which stomach acid or bile irritates the food pipe lining.",
    dos: ["Eat smaller meals", "Avoid lying down for 3 hours after eating", "Elevate head while sleeping"],
    donts: ["Eat trigger foods (spicy, fatty)", "Smoke", "Drink alcohol"],
    consult_if: ["Difficulty swallowing", "Chest pain radiating to arm/jaw", "Frequent vomiting"],
    typical_duration: "Chronic/Recurrent",
    remedies: ["Chewing gum", "Aloe vera juice"],
  },
  {
    name: "Conjunctivitis (Pink Eye)",
    category: "Low Risk - Eye",
    symptoms: ["eye redness", "itching", "tearing", "discharge"],
    description: "Inflammation or infection of the outer membrane of the eyeball and the inner eyelid.",
    dos: ["Use warm/cold compress", "Keep eyes clean", "Wash hands frequently"],
    donts: ["Touch or rub eyes", "Share towels or pillows", "Wear contact lenses"],
    consult_if: ["Severe eye pain", "Blurred vision", "Sensitivity to light"],
    typical_duration: "7–14 days",
    remedies: ["Warm washcloth compress", "Artificial tears"],
  },
];
